INSERT INTO USER VALUES (1, 'ok', 'ok', 'ok');
INSERT INTO USER VALUES (2, 'ok', 'ok', 'ok');

INSERT INTO USER_ROLE VALUES (1, 0);
INSERT INTO USER_ROLE VALUES (1, 1);


INSERT INTO GOODS_ORDER VALUES (1, 'address 1', 'client 1', CURRENT_DATE(), 1);
INSERT INTO GOODS_ORDER VALUES (2, 'address 2', 'client 2', CURRENT_DATE(), 1);
INSERT INTO GOODS_ORDER VALUES (3, 'address 3', 'client 3', CURRENT_DATE(), 2);

INSERT INTO GOODS VALUES (1, 'Brush', 100);
INSERT INTO GOODS VALUES (2, 'Shampoo', 200);
INSERT INTO GOODS VALUES (3, 'Soap', 150);

INSERT INTO ORDER_LINE VALUES (1, 10, 2, 1);
INSERT INTO ORDER_LINE VALUES (2, 20, 3, 1);
INSERT INTO ORDER_LINE VALUES (3, 15, 1, 2);
INSERT INTO ORDER_LINE VALUES (4, 10, 3, 2);
INSERT INTO ORDER_LINE VALUES (5, 10, 1, 3);
INSERT INTO ORDER_LINE VALUES (6, 15, 2, 3);
INSERT INTO ORDER_LINE VALUES (7, 30, 3, 3);